version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongo_database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./database/db_data:/data/db
  

  stt:
    build:
      context: ./stt
    runtime: nvidia
    container_name: stt-module
    environment:
      - ENV=DockerEnv
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=user
      - RABBITMQ_PASS=password
      - DB_CONNECTION_STRING=mongodb://admin:password@mongodb:27017/
      - AUDIO_DIR=/app/uploads
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - rabbitmq
      - mongodb