[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "semantic_analysis_system"
version = "0.1.0"
description = "System for Processing and Semantic Analysis of Radio Broadcast Transcripts"

[tool.setuptools]
packages = ["nlp", "stt", "api", "database", "rabbitmq"]